name: stripes_ui
description: A new Flutter package project.
version: 1.0.2
homepage: https://github.com/dylanb7/stripes_ui
publish_to: none

#stripes_backend_helper:
#    git:
#       url: https://github.com/dylanb7/stripes_backend_helper
#       branch: master

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  duration: ^3.0.13
  rive: ^0.14.0-dev.4
  markdown_widget: ^2.3.2+8
  flex_color_scheme: ^8.3.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  select_field: ^2.0.0
  custom_sliding_segmented_control: ^1.8.3
  flutter_email_sender: ^7.0.0
  add_2_calendar: ^3.0.1
  go_router: ^16.0.0
  equatable: ^2.0.3
  pin_code_fields: ^7.3.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.9
  badges: ^3.1.1
  fl_chart: ^1.0.0
  csv: ^5.0.1
  async: ^2.9.0
  collection: ^1.17.0
  email_validator: ^2.1.17
  rxdart: ^0.27.7
  uuid: ^4.5.1
  flutter_riverpod: ^2.5.1
  share_plus: ^10.0.0
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.3
  stripes_backend_helper:
    path: ../stripes_backend_helper

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  custom_lint: ^0.6.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: packages/stripes_ui/assets/fonts/Inter/Inter-VariableFont_slnt,wght.ttf
  assets:
    - packages/stripes_ui/assets/images/Blue_Poop.png
    - packages/stripes_ui/assets/images/Brown_Poop.png
    - packages/stripes_ui/assets/images/StripesLogo.png
    - packages/stripes_ui/assets/images/poop1.png
    - packages/stripes_ui/assets/images/poop2.png
    - packages/stripes_ui/assets/images/poop3.png
    - packages/stripes_ui/assets/images/poop4.png
    - packages/stripes_ui/assets/images/poop5.png
    - packages/stripes_ui/assets/images/poop6.png
    - packages/stripes_ui/assets/images/poop7.png
    - packages/stripes_ui/assets/images/abdomin.png
    - packages/stripes_ui/assets/images/pain_faces_0.png
    - packages/stripes_ui/assets/images/pain_faces_1.png
    - packages/stripes_ui/assets/images/pain_faces_2.png
    - packages/stripes_ui/assets/images/pain_faces_3.png
    - packages/stripes_ui/assets/images/pain_faces_4.png
    - packages/stripes_ui/assets/svg/pain_face_0.svg
    - packages/stripes_ui/assets/svg/pain_face_1.svg
    - packages/stripes_ui/assets/svg/pain_face_2.svg
    - packages/stripes_ui/assets/svg/pain_face_3.svg
    - packages/stripes_ui/assets/svg/pain_face_4.svg
    - packages/stripes_ui/assets/svg/pain_face_5.svg
    - packages/stripes_ui/assets/svg/muffin_icon.svg
    - packages/stripes_ui/assets/rive/stripes_header.riv
